=== VijayEluri/R2AD-JavaFX-Cloud-Client/src/org/occi/model/schema/OCCI-XML-02.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
    Description: This is not per OCCI spec.  This is a legacy ON example.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.occi-pilot.org"
	         xmlns:occi="http://www.occi-pilot.org"
           attributeFormDefault="unqualified"
           elementFormDefault="unqualified"
>
  <xs:simpleType name="positiveFloat">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="RelatedType">
    <xs:restriction base="xs:NMTOKEN"/>
  </xs:simpleType>

  <xs:simpleType name="ComputeArchitectureEnum">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="x86" />
      <xs:enumeration value="x64" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ComputeStatusEnum">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="active" />
      <xs:enumeration value="inactive" />
      <xs:enumeration value="suspended" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NetworkAllocationEnum">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="auto" />
      <xs:enumeration value="dhcp" />
      <xs:enumeration value="manual" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NetworkVlanType">
    <xs:restriction base="xs:unsignedInt">
      <xs:maxInclusive value="4095" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="StorageStatusEnum" >
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="online" />
      <xs:enumeration value="offline" />
      <xs:enumeration value="degraded" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="OCCI" type="occi:OCCI" />
    <xs:complexType name="OCCI" >
    <xs:sequence>
      <xs:element name="kind" type="occi:kind" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="compute" type="occi:compute" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="network" type="occi:network" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="storage" type="occi:storage" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="kind" type="occi:kind" />
  <xs:complexType name="kind">
    <xs:sequence>
      <xs:element name="compute" type="occi:compute" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="network" type="occi:network" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="storage" type="occi:storage" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:NMTOKEN" use="required" />
    <xs:attribute name="related" type="occi:RelatedType" use="optional" />
    <xs:attribute name="title" type="xs:string" use="optional" />
    <xs:attribute name="summary" type="xs:string" use="optional" />
  </xs:complexType>
  
  <xs:element name="compute" type="occi:compute" />
  <xs:complexType name="compute">
    <xs:sequence minOccurs="0" maxOccurs="unbounded" >
      <xs:element name="link" type="xs:anyURI" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:NMTOKEN" use="required" />
    <xs:attribute name="related" type="occi:RelatedType" use="optional" />
    <xs:attribute name="title" type="xs:string" use="optional" />
    <xs:attribute name="summary" type="xs:string" use="optional" />
    <xs:attribute name="cores" type="occi:positiveFloat" use="optional" />
    <xs:attribute name="architecture" type="occi:ComputeArchitectureEnum" use="optional" />
    <xs:attribute name="hostname" type="xs:string" use="required" />
    <xs:attribute name="speed" type="occi:positiveFloat" use="required" />
    <xs:attribute name="memory" type="occi:positiveFloat" use="required" />
    <xs:attribute name="status" type="occi:ComputeStatusEnum" use="required" />
  </xs:complexType>
  
  <xs:element name="network" type="occi:network"/>
  <xs:complexType name="network">
    <xs:sequence minOccurs="0">
      <xs:element name="link" type="xs:anyURI" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:NMTOKEN" use="required" />
    <xs:attribute name="related" type="occi:RelatedType" use="optional" />
    <xs:attribute name="allocation" type="occi:NetworkAllocationEnum" use="optional" />
    <xs:attribute name="title" type="xs:string" use="optional" />
    <xs:attribute name="summary" type="xs:string" use="optional" />
    <xs:attribute name="address" type="xs:string" use="optional" />
    <xs:attribute name="gateway" type="xs:string" use="optional" />
    <xs:attribute name="vlan" type="occi:NetworkVlanType" use="optional" />
    <xs:attribute name="label" type="xs:string" use="optional" />
  </xs:complexType>
  
  <xs:element name="storage" type="occi:storage"/>
  <xs:complexType name="storage">
    <xs:sequence minOccurs="0">
      <xs:element name="link" type="xs:anyURI" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:NMTOKEN" use="required" />
    <xs:attribute name="related" type="occi:RelatedType" use="optional" />
    <xs:attribute name="title" type="xs:string" use="optional" />
    <xs:attribute name="summary" type="xs:string" use="optional" />
    <xs:attribute name="size" type="occi:positiveFloat" use="optional" />
    <xs:attribute name="status" type="occi:StorageStatusEnum" use="optional" />
  </xs:complexType>
</xs:schema>

=== VijayEluri/R2AD-JavaFX-Cloud-Client/src/org/occi/model/schema/OCCI-XML-02-ref-doc.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
    Description: This is not per OCCI spec.  This is a legacy ON example.
-->
<OCCI 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.alloycloud.com"
      xsi:schemaLocation="http://www.alloycloud.com occi-xml-02.xsd"
      >

  <kind  id="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="My VM1" summary="A test Vitrual Machine 1">
    <compute id="VM1-E9B6EA5D-AFCD-43a8-B100-B72A0B841CD8" related="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Mains" summary="Main CPUs" cores="" architecture="" hostname=""></compute>
    <compute id="VM1-F9B6EA5D-BFCE-43a8-B100-B72A0B841CD8" related="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Spare" summary="Spared for Failover" cores="2" architecture="x86" hostname="Wally"></compute>

    <network id="VM1-AC3F20FA-AB76-4fb2-AE31-A81A9467588C" related="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" allocation="dhcp"></network>
    <network id="VM1-AC3F20FB-AB76-4fb2-AE32-A81A9467588C" related="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Public" summary="Public"  address="" gateway="" allocation="auto"></network>
    <network id="VM1-AC3F20FC-AB76-4fb2-AE32-A81A9467588C" related="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Mgt" summary="Mgt" vlan="22" label="Management Segment" address="172.31.1.10" gateway="172.31.1.1" allocation="manual"></network>
    <network id="VM1-AC3F20FD-AB76-4fb2-AE32-A81A9467588C" related="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Heartbeat" summary="" vlan="12" label="Hearbeat Segment" allocation="dhcp"></network>

    <storage id="VM1-E9B6EA5D-AFCD-43a8-B100-B72A0B841CD8" related="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Disk1" summary="Main Disk" size="2000000000" status="offline">
      <link>http://www.cdmi-pilot.org/demo/CDMI-DISK-2-VM1</link>
    </storage>
    <storage id="VM1-E9B6EA5D-AFCD-43a8-B100-B72A0B841CD9" related="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Disk2" summary="Transaction Disk" size="2000000000" status="degraded">
      <link>http://www.cdmi-pilot.org/demo/CDMI-DISK-2-VM1</link>
    </storage>
    <storage id="VM1-E9B6EA5D-AFCD-43a8-B100-B72A0B841CDA" related="VM1-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Spare" summary="Spared for Failover" size="2000000000" status="online">
      <link>http://www.cdmi-pilot.org/demo/CDMI-SPARE-VM1</link>
    </storage>
  </kind>

  <kind  id="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="My VM2" summary="A test Vitrual Machine 2">
    <compute id="VM2-E9B6EA5D-AFCD-43a8-B100-B72A0B841CD8" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Mains" summary="Main CPUs" cores="" architecture="" hostname=""></compute>
    <compute id="VM2-E9B6EA5D-BFCE-43a8-B100-B72A0B841CD8" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Spare" summary="Spared for Failover" cores="2" architecture="x86" hostname="Wally"></compute>

    <network id="VM2-AC3F20FA-AB76-4fb2-AE31-A81A9467588C" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" allocation="dhcp"></network>
    <network id="VM2-AC3F20FB-AB76-4fb2-AE32-A81A9467588C" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Public" summary="Public"  address="" gateway="" allocation="auto"></network>
    <network id="VM2-AC3F20FC-AB76-4fb2-AE32-A81A9467588C" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Mgt" summary="Mgt" vlan="22" label="Management Segment" address="172.31.1.10" gateway="172.31.1.1" allocation="manual"></network>
    <network id="VM2-AC3F20FD-AB76-4fb2-AE32-A81A9467588C" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Heartbeat" summary="" vlan="12" label="Hearbeat Segment" allocation="dhcp"></network>

    <memory id="VM2-AC3F20FD-AB76-4fb2-AE31-A81A9467588D" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="RamDisk" summary="System Memory for RamDisk" size="1000000"></memory>
    <memory id="VM2-AC3F20FD-AB76-4fb2-AE31-A81A9467588E" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Shared" summary="System Memory for Shared" size="1000000"></memory>
    <memory id="VM2-AC3F20FD-AB76-4fb2-AE31-A81A9467588F" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="RamDisk" summary="System Memory for RamDisk" size="1000000"></memory>

    <storage id="VM2-E9B6EA5D-AFCD-43a8-B100-B72A0B841CD8" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Disk1" summary="Main Disk" size="2000000000" status="offline">
      <link>http://www.cdmi-pilot.org/demo/CDMI-DISK-2-VM2</link>
    </storage>
    <storage id="VM2-E9B6EA5D-AFCD-43a8-B100-B72A0B841CD" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Disk2" summary="Transaction Disk" size="2000000000" status="degraded">
      <link>http://www.cdmi-pilot.org/demo/CDMI-DISK-2-VM2</link>
    </storage>
    <storage id="VM2-E9B6EA5D-AFCD-43a8-B100-B72A0B841CDA" related="VM2-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Spare" summary="Spared for Failover" size="2000000000" status="online">
      <link>http://www.cdmi-pilot.org/demo/CDMI-SPARE-VM2</link>
    </storage>
  </kind>

  <kind  id="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="My VM2" summary="A test Vitrual Machine 2">
    <compute id="VM3-E9B6EA5D-AFCD-43a8-B100-B72A0B841CD8" related="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Mains" summary="Main CPUs" cores="" architecture="" hostname=""></compute>
    <compute id="VM3-E9B6EA5D-BFCE-43a8-B100-B72A0B841CD8" related="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Spare" summary="Spared for Failover" cores="2" architecture="x86" hostname="Wally"></compute>

    <network id="VM3-AC3F20FA-AB76-4fb2-AE31-A81A9467588C" related="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" allocation="dhcp"></network>
    <network id="VM3-AC3F20FB-AB76-4fb2-AE32-A81A9467588C" related="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Public" summary="Public"  address="" gateway="" allocation="auto"></network>
    <network id="VM3-AC3F20FC-AB76-4fb2-AE32-A81A9467588C" related="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Mgt" summary="Mgt" vlan="22" label="Management Segment" address="172.31.1.10" gateway="172.31.1.1" allocation="manual"></network>
    <network id="VM3-AC3F20FD-AB76-4fb2-AE32-A81A9467588C" related="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Heartbeat" summary="" vlan="12" label="Hearbeat Segment" allocation="dhcp"></network>

    <storage id="VM3-E9B6EA5D-AFCD-43a8-B100-B72A0B841CD8" related="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Disk1" summary="Main Disk" size="2000000000" status="offline">
      <link>http://www.cdmi-pilot.org/demo/CDMI-DISK-2-VM3</link>
    </storage>
    <storage id="VM3-E9B6EA5D-AFCD-43a8-B100-B72A0B841CD9" related="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Disk2" summary="Transaction Disk" size="2000000000" status="degraded">
      <link>http://www.cdmi-pilot.org/demo/CDMI-DISK-2-VM3</link>
    </storage>
    <storage id="VM3-E9B6EA5D-AFCD-43a8-B100-B72A0B841CDA" related="VM3-6D5FB012-1ED6-4ce2-A466-19E862DB795B" title="Spare" summary="Spared for Failover" size="2000000000" status="online">
      <link>http://www.cdmi-pilot.org/demo/CDMI-SPARE-VM3</link>
    </storage>
  </kind>

</OCCI>
